### ISSUE TITLE
Feature Request: Door Status

### ISSUE THREAD

**Issue by Spectranis** [fscs/website-server#8]
Idee: Auf der Website den Status der Türe darstellen, damit man über diese sehen kann, ob die FS gerae geöffnet ist.

Hintergrund: Früher war es möglich über die Website zu sehen, ob die FS offen ist. Daher wäre es ggf nice to have sowas wieder einzuführen.
Beispiel dafür wäre z.B. der "Raumstatus" vom Chaosdorf: https://wiki.chaosdorf.de/Chaosdorf

Requirements:
- z.B. Arduino mit einem Sensor, der prüfen kann ob die Tür geschlossen ist
- Bei Änderung schickt PI ein Update an eine Schnittstelle zur Website (ToDefine)

**Comment by Spectranis** [comment]
ToDo:

- benötigte Hardware raussuchen und Preis in Erfahrung bringen (verwenden z.B. Abfahrstmonitor PI oder Mete PI zusatzfunktion aufbrummen)
- Sitzungstop zu den Kosten anlegen

**Comment by MarchCraft** [comment]
Magnetsensor für die Tür ist bestellt

**Comment by Spectranis** [comment]
Feature request update:
- Sensor oben am Türrahmen befestigen, damit @MarchCraft mit dem Kopf besser gegenstoßen kann.

**Comment by MarchCraft** [comment]
Fertig

**Comment by MarchCraft** [comment]
Not working anymore because there was auth added

**Comment by MarchCraft** [comment]
Working and added auth
